/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "Pin_ADC_aliases.h"
#include "Pin_ADC.h"
#include "PWM_Motores.h"
#include "CLK.h"
#include "MotorD_aliases.h"
#include "MotorD.h"
#include "MotorI_aliases.h"
#include "MotorI.h"
#include "UART.h"
#include "IRQRX.h"
#include "LED_aliases.h"
#include "LED.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "PWM_Dir.h"
#include "Clock_1.h"
#include "PWMdir_I_aliases.h"
#include "PWMdir_I.h"
#include "PWMdir_D_aliases.h"
#include "PWMdir_D.h"
#include "INMI_aliases.h"
#include "INMI.h"
#include "INMD_aliases.h"
#include "INMD.h"
#include "Clock_2.h"
#include "Pin_Ascensor_aliases.h"
#include "Pin_Ascensor.h"
#include "Ascensor.h"
#include "PWM_Door.h"
#include "PWMdoor_aliases.h"
#include "PWMdoor.h"
#include "Lanzamiento_aliases.h"
#include "Lanzamiento.h"
#include "INMA_aliases.h"
#include "INMA.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

