/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_Motores_P.h"
#include "CLK.h"
#include "MotorPD_aliases.h"
#include "MotorPD.h"
#include "MotorPI_aliases.h"
#include "MotorPI.h"
#include "UART.h"
#include "IRQRX.h"
#include "LED_aliases.h"
#include "LED.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "PWM_Motores_A.h"
#include "Clock_1.h"
#include "MotorAI_aliases.h"
#include "MotorAI.h"
#include "MotorAD_aliases.h"
#include "MotorAD.h"
#include "IMPI_aliases.h"
#include "IMPI.h"
#include "IMPD_aliases.h"
#include "IMPD.h"
#include "Pin_Ascensor_aliases.h"
#include "Pin_Ascensor.h"
#include "PWM_D_A.h"
#include "PWMdoor_aliases.h"
#include "PWMdoor.h"
#include "Lanzamiento_aliases.h"
#include "Lanzamiento.h"
#include "IMAS_aliases.h"
#include "IMAS.h"
#include "IML_aliases.h"
#include "IML.h"
#include "IMAI_aliases.h"
#include "IMAI.h"
#include "IMAD_aliases.h"
#include "IMAD.h"
#include "ISR_FOTO.h"
#include "INFRA_aliases.h"
#include "INFRA.h"
#include "TIMER.h"
#include "ISR_TIMER.h"
#include "Clock.h"
#include "UART_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

